### PR TITLE
add function catmaid_get_connector_info and documentation

### PR DESCRIPTION
**Pull request by zhihaozheng**
#52

### CODE REVIEW

**Comment by jefferis** [comment]
@zhihaozheng Many thanks for this. You'll see it's now merged with a few minor changes (mostly to docs) but I also decided to change the name to `catmaid_get_connectors_between`.

**Comment by zhihaozheng** [comment]
@jefferis Thank you. I am glad it is accepted. Good name change. Agreed the original name was confusing.

**Comment by jefferis** [comment]
Actually @zhihaozheng I did make one more change in ee1d14a593e1d72a67995d09be1cf93f39ad4db2 where I changed the organisation of the results. In general I prefer to have a normalised data.frame where each column is a simple type rather than a list. Comments welcome though.

**Comment by zhihaozheng** [comment]
@jefferis Agreed. It is a good practice and also better consistent with xyz matrix in the nat neuron object.

**Pull request merged**
