### PR TITLE
Mockhttptest

### PR DESCRIPTION
**Pull request by SridharJagannathan**
@Greg: I have made preliminary implementation for a single file `test-annotation.R`, please check and give me your overall comments.
Added preliminary testcases for `test-annotation.R` using the `httptest` package.
Step 1) Run the file `configure_httptest.R`
Step 2)Rename the folder structure as mentioned in step 5 of the file `configure_httptest.r`
Step 3) Run the `test-annotation.R` offline to check if the caching works

### CODE REVIEW

**Comment by jefferis** [comment]
Hi Sri, That's looking promising. There are a few additional considerations though.

1. I'd like to retain tests against a live server as well as tests against mocked data
2. but for the former, the tests could be relaxed to check structure rather than detailed response values
3. The saved mocked test result will be visible in the GitHub repository. Therefore only publicly available data should be used (we could make an exception for less sensitive stuff like annotation or user lists, but definitely no skeleton / connectivity information).
4. The easiest thing would be to run as many tests as possible against https://l1em.catmaid.virtualflybrain.org either live or using mocked/cached data.
5. For mocked tests, where possible try to avoid very test results since they will inflate the package size

**Comment by SridharJagannathan** [comment]
@jefferis I have added support for testing against a public live server using the following env var
`Sys.setenv(MOCK_BYPASS = "true") #"true" (public live server) , "capture" (mock server) `
We can possibly put this env var in a config file or on travis env?

**Comment by jefferis** [comment]
> @jefferis I have added support for testing against a public live server using the following env var
Sys.setenv(MOCK_BYPASS = "true") #"true" (public live server) , "capture" (mock server) 
We can possibly put this env var in a config file or on travis env?

I was hoping to have both tests, with different kinds of  expectations, rather than switching between one or the other.

**Comment by SridharJagannathan** [comment]
I have made preliminary implementations for both mock and public live server, can you please check. Once this design is Ok, then I will add detailed test cases for mock and just structure for live server

**Comment by jefferis** [comment]
Hi @SridharJagannathan, although you've worked out the underlying strategy I'm afraid this isn't there yet:

* on travis there is no error, but that's because many tests are skipped because there are no valid CATMAID credentials. I'm afraid that's not obvious from the travis output, but it's definitely what's happen.
* on my machine some of the tests fail because the connection is not specified explicitly for most of the tests – sometimes it picks up the default credentials on my machine (adult FAFB server) other times something the connection for the last server that was logged into.

I think every single test needs to have an explicitly specified connection, whether it is a test against a mock connection or against a live server. I'll update some of the `test-*` files to try and make this clear.

**Comment by SridharJagannathan** [comment]
Hi @jefferis, I'm surprised by this in my mac I have removed all the environmental variables and re run the tests and only 2 of them get skipped, please see the attached screenshot
Screenshot 2019-06-17 at 09 44 52

**Comment by jefferis** [comment]
@SridharJagannathan My apologies – all working perfectly. Somehow managed not to update to latest version of your code. Will merge now.

**Pull request merged**
