### PR TITLE
Feature/update neurons

### PR DESCRIPTION
**Pull request by jefferis**
Still thinking about these additions from @alexanderbates

### CODE REVIEW

**Comment by jefferis** [comment]
split away from #131

**Comment by jefferis** [comment]
Split away from #130

**Comment by jefferis** [comment]
@alexanderbates I would suggest combining these into a single function e.g. `update_neuronlist`. In general if a function does something closely related and returns the same kind of object then I would consider combining. In this case you have an argument to control which kind of update is required (with a default to update everything). Note also that `read.neurons.catmaid` actually fetches neuron names.

**Comment by jefferis** [comment]
@alexanderbates I would suggest combining these into a single function e.g. `update_neuronlist`. In general if a function does something closely related and returns the same kind of object then I would consider combining. In this case you have an argument to control which kind of update is required (with a default to update everything). Note also that `read.neurons.catmaid` actually fetches neuron names.

**Comment by alexanderbates** [comment]
Okay, done!

**Pull request merged**
